// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIChat(arg1) {
  return window['go']['main']['App']['AIChat'](arg1);
}

export function AIComplete(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AIComplete'](arg1, arg2, arg3, arg4);
}

export function AIGetConfig() {
  return window['go']['main']['App']['AIGetConfig']();
}

export function AIUpdateConfig(arg1) {
  return window['go']['main']['App']['AIUpdateConfig'](arg1);
}

export function AppendEgoMemory(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppendEgoMemory'](arg1, arg2, arg3);
}

export function BuildExe(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildExe'](arg1, arg2, arg3);
}

export function BuildWithConfig(arg1, arg2) {
  return window['go']['main']['App']['BuildWithConfig'](arg1, arg2);
}

export function CompileAndRun(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CompileAndRun'](arg1, arg2, arg3, arg4);
}

export function ConvertChineseToGo(arg1) {
  return window['go']['main']['App']['ConvertChineseToGo'](arg1);
}

export function ConvertCodeRowsToGo(arg1) {
  return window['go']['main']['App']['ConvertCodeRowsToGo'](arg1);
}

export function CreateProject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DownloadModelFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadModelFile'](arg1, arg2);
}

export function ExportGoCode(arg1) {
  return window['go']['main']['App']['ExportGoCode'](arg1);
}

export function GetAllFunctions() {
  return window['go']['main']['App']['GetAllFunctions']();
}

export function GetAllProjects() {
  return window['go']['main']['App']['GetAllProjects']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetEgoMemorySummary(arg1) {
  return window['go']['main']['App']['GetEgoMemorySummary'](arg1);
}

export function GetFavoriteProjects() {
  return window['go']['main']['App']['GetFavoriteProjects']();
}

export function GetFunctionSuggestions(arg1) {
  return window['go']['main']['App']['GetFunctionSuggestions'](arg1);
}

export function GetFunctionsByCategory(arg1) {
  return window['go']['main']['App']['GetFunctionsByCategory'](arg1);
}

export function GetModelDownloadStatus(arg1) {
  return window['go']['main']['App']['GetModelDownloadStatus'](arg1);
}

export function GetModelsDir() {
  return window['go']['main']['App']['GetModelsDir']();
}

export function GetProjectTemplates() {
  return window['go']['main']['App']['GetProjectTemplates']();
}

export function GetRecentProjects(arg1) {
  return window['go']['main']['App']['GetRecentProjects'](arg1);
}

export function GetSupportedPlatforms() {
  return window['go']['main']['App']['GetSupportedPlatforms']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitEgoMemory(arg1, arg2) {
  return window['go']['main']['App']['InitEgoMemory'](arg1, arg2);
}

export function IsProgramRunning() {
  return window['go']['main']['App']['IsProgramRunning']();
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function OpenDialog() {
  return window['go']['main']['App']['OpenDialog']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function ReadEgoMemory(arg1) {
  return window['go']['main']['App']['ReadEgoMemory'](arg1);
}

export function SaveDialog() {
  return window['go']['main']['App']['SaveDialog']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SearchProjects(arg1) {
  return window['go']['main']['App']['SearchProjects'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectSavePath() {
  return window['go']['main']['App']['SelectSavePath']();
}

export function StopProgram() {
  return window['go']['main']['App']['StopProgram']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3);
}

export function ValidateCode(arg1) {
  return window['go']['main']['App']['ValidateCode'](arg1);
}

export function WriteEgoMemory(arg1, arg2) {
  return window['go']['main']['App']['WriteEgoMemory'](arg1, arg2);
}
