// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {core} from '../models';
import {models} from '../models';

export function AIChat(arg1:Array<services.ChatMessage>):Promise<services.ChatResponse>;

export function AIComplete(arg1:string,arg2:string,arg3:string,arg4:number):Promise<services.CompletionResponse>;

export function AIGetConfig():Promise<services.AIConfig>;

export function AIUpdateConfig(arg1:services.AIConfig):Promise<void>;

export function AppendEgoMemory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BuildExe(arg1:string,arg2:string,arg3:string):Promise<services.BuildResult>;

export function BuildWithConfig(arg1:string,arg2:services.BuildConfig):Promise<services.BuildResult>;

export function CompileAndRun(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<services.BuildResult>;

export function ConvertChineseToGo(arg1:string):Promise<string>;

export function ConvertCodeRowsToGo(arg1:Array<core.CodeRowData>):Promise<string>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Project>;

export function DeleteProject(arg1:number):Promise<void>;

export function DownloadModelFile(arg1:string,arg2:string):Promise<void>;

export function ExportGoCode(arg1:string):Promise<string>;

export function GetAllFunctions():Promise<Array<core.ChineseFunction>>;

export function GetAllProjects():Promise<Array<models.Project>>;

export function GetCategories():Promise<Array<string>>;

export function GetEgoMemorySummary(arg1:string):Promise<string>;

export function GetFavoriteProjects():Promise<Array<models.Project>>;

export function GetFunctionSuggestions(arg1:string):Promise<Array<core.ChineseFunction>>;

export function GetFunctionsByCategory(arg1:string):Promise<Array<core.ChineseFunction>>;

export function GetModelDownloadStatus(arg1:string):Promise<Record<string, any>>;

export function GetModelsDir():Promise<string>;

export function GetProjectTemplates():Promise<Array<models.ProjectTemplate>>;

export function GetRecentProjects(arg1:number):Promise<Array<models.Project>>;

export function GetSupportedPlatforms():Promise<Array<Record<string, string>>>;

export function GetTemplates():Promise<Array<core.CodeTemplate>>;

export function Greet(arg1:string):Promise<string>;

export function InitEgoMemory(arg1:string,arg2:string):Promise<void>;

export function IsProgramRunning():Promise<boolean>;

export function LoadFile(arg1:string):Promise<string>;

export function OpenDialog():Promise<string>;

export function OpenProject(arg1:number):Promise<models.Project>;

export function ReadEgoMemory(arg1:string):Promise<string>;

export function SaveDialog():Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SearchProjects(arg1:string):Promise<Array<models.Project>>;

export function SelectFolder():Promise<string>;

export function SelectSavePath():Promise<string>;

export function StopProgram():Promise<void>;

export function ToggleFavorite(arg1:number):Promise<boolean>;

export function UpdateProject(arg1:number,arg2:string,arg3:string):Promise<void>;

export function ValidateCode(arg1:string):Promise<Array<string>>;

export function WriteEgoMemory(arg1:string,arg2:string):Promise<void>;
